# generated by datamodel-codegen:
#   filename:  GetDepositAddressRequest.json
#   timestamp: 2025-04-06T21:23:52+00:00

from __future__ import annotations

from pydantic import BaseModel


class GetDepositAddressRequest(BaseModel):
    layer2_address_pubkey: str = None
    nonce: str = None
    signature: str = None
