# generated by datamodel-codegen:
#   filename:  RequestWithdrawalRequest.json
#   timestamp: 2025-04-06T21:23:56+00:00

from __future__ import annotations

from pydantic import BaseModel


class RequestWithdrawalRequest(BaseModel):
    amount: int = None
    layer1_withdrawal_address: str = None
    nonce: str = None
    signature: str = None
    source_address_public_key: str = None
