# generated by datamodel-codegen:
#   filename:  PushTransactionRequest.json
#   timestamp: 2025-04-06T21:23:48+00:00

from __future__ import annotations


from pydantic import BaseModel


class PushTransactionRequest(BaseModel):
    amount: int = None
    destination_address_public_key: str = None
    fee: int = None
    signature: str = None
    source_address_public_key: str = None
    transaction_id: str = None
