# generated by datamodel-codegen:
#   filename:  GetNodeInfoResponse.json
#   timestamp: 2025-04-26T22:30:04+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from .CommonResponse import CommonResponse


class Layer1NetworkInfo(BaseModel):
    minimum_transaction_amount: int = None


class Version(BaseModel):
    API_version: int = None
    major_version: int = None
    minor_version: int = None
    patch_version: int = None


class NodeInfo(BaseModel):
    asset_id: int = None
    deposit_address_derivation_path: str = None
    layer1_network_info: Layer1NetworkInfo = None
    node_id: str = None
    node_name: str = None
    onboarding_deposit_signing_key_pubkey: str = None
    version: Version = None


class GetNodeInfoResponse(CommonResponse):
    node_info: NodeInfo = None
