# generated by datamodel-codegen:
#   filename:  GetTransactionResponse.json
#   timestamp: 2025-04-26T22:29:58+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from .CommonResponse import CommonResponse


class GetTransactionsResponseTransaction(BaseModel):
    amount: int = None
    destination_address_pubkey: str = None
    fee: int = None
    layer1_transaction_id: str = None
    layer2_withdrawal_id: str = None
    signature: str = None
    signature_date: str = None
    source_address_pubkey: str = None
    timestamp: int = None
    transaction_id: str = None
    transaction_type: int = None


class GetTransactionResponse(CommonResponse):
    transaction: GetTransactionsResponseTransaction | None = None
    transaction_id: str = None
