# generated by datamodel-codegen:
#   filename:  Layer1AuditReportResponse.json
#   timestamp: 2025-04-26T22:30:09+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel

from .CommonResponse import CommonResponse


class Layer1AddressBalance(BaseModel):
    balance: int = None
    layer1Address: str = None


class Layer1AuditReportResponse(CommonResponse):
    addressBalances: List[Layer1AddressBalance] = None
    blockHeight: int = None
    ready: bool = None
    totalBalance: int = None
