# generated by datamodel-codegen:
#   filename:  GetTransactionResponse.json
#   timestamp: 2025-04-26T22:29:58+00:00

from __future__ import annotations

from pydantic import BaseModel
from .common_response import CommonResponse


class GetTransactionsResponseTransaction(BaseModel):
    amount: int
    destination_address_pubkey: str
    fee: int
    layer1_transaction_id: str
    layer2_withdrawal_id: str
    signature: str
    signature_date: str
    source_address_pubkey: str
    timestamp: int
    transaction_id: str
    transaction_type: int


class GetTransactionResponse(CommonResponse):
    transaction: GetTransactionsResponseTransaction | None = None
    transaction_id: str
