# generated by datamodel-codegen:
#   filename:  Layer1AuditReportResponse.json
#   timestamp: 2025-04-26T22:30:09+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel

from .common_response import CommonResponse


class Layer1AddressBalance(BaseModel):
    balance: int
    layer1Address: str


class GetLayer1AuditReportResponse(CommonResponse):
    addressBalances: List[Layer1AddressBalance]
    blockHeight: int
    ready: bool
    totalBalance: int
