# generated by datamodel-codegen:
#   filename:  GetBalanceResponse.json
#   timestamp: 2025-04-26T22:29:55+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel

from .common_response import CommonResponse

class GetBalanceResponseBalance(BaseModel):
    address_found: bool = None 
    balance: int = None
    public_key: str = None


class GetBalanceResponse(CommonResponse):
    balance: List[GetBalanceResponseBalance] = None
