# generated by datamodel-codegen:
#   filename:  GetTransactionResponse.json
#   timestamp: 2025-04-26T22:29:58+00:00

from __future__ import annotations

from .common_response import CommonResponse
from .get_transactions_response import GetTransactionsResponseTransaction


class GetTransactionResponse(CommonResponse):
    transaction: GetTransactionsResponseTransaction | None = None
    transaction_id: str
