# generated by datamodel-codegen:
#   filename:  GetNodeInfoResponse.json
#   timestamp: 2025-04-26T22:30:04+00:00

from __future__ import annotations


from pydantic import BaseModel
from .common_response import CommonResponse


class Layer1NetworkInfo(BaseModel):
    minimum_transaction_amount: int


class Version(BaseModel):
    API_version: int
    major_version: int
    minor_version: int
    patch_version: int

        
class NodeInfo(BaseModel):
    asset_id: str
    deposit_address_derivation_path: str
    layer1_network_info: Layer1NetworkInfo
    node_id: str
    node_name: str
    onboarding_deposit_signing_key_pubkey: str
    version: Version


class GetNodeInfoResponse(CommonResponse):
    node_info: NodeInfo
