FROM ghcr.io/astral-sh/uv:python3.12-bookworm as builder

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq5 \
    && rm -rf /var/lib/apt/lists/*

# Copy dependency files (copy README.md since hatchling.build requires it to buld)
COPY layer2ledgerbatched/pyproject.toml layer2ledgerbatched/uv.lock layer2ledgerbatched/
COPY packages/config-models packages/config-models
#COPY . /app/layer2ledgerapihandler/
#COPY pyproject.toml uv.lock README.md ./app/layer2ledgerapihandler/

# Change workdir to the layer2ledgerapihandler folder
#WORKDIR /app/layer2ledgerapihandler

# Install dependencies WITHOUT the local project
RUN cd layer2ledgerbatched && uv sync --frozen --no-install-project --no-dev

# Copy layer2ledgerapihandler source code
COPY layer2ledgerbatched layer2ledgerbatched/

# Install the service itself
RUN cd layer2ledgerbatched && uv sync --frozen --no-dev

# Verify installation
#RUN cd layer2ledgerbatched && uv pip show layer2ledgerbatched && echo "✓ Package installed successfully"

# Runtime stage
FROM python:3.12-slim

WORKDIR /app

# Copy only what this service needs
COPY --from=builder /app/layer2ledgerbatched/.venv /app/layer2ledgerbatched/.venv
COPY --from=builder /app/layer2ledgerbatched /app/layer2ledgerbatched
COPY --from=builder /app/packages/config-models /app/packages/config-models

ENV PATH="/app/layer2ledgerbatched/.venv/bin:$PATH"
ENV PYTHONUNBUFFERED=1

CMD ["python", "-m", "layer2ledgerdbwriter.main"]