FROM oven/bun:1.3.3 AS base
WORKDIR /app

FROM base AS pruner
COPY . .
RUN bunx turbo@2.8.14 prune @openl2/layer2ledger --docker

FROM base AS installer
COPY --from=pruner /app/out/json/ .
RUN bun install --no-save
COPY --from=pruner /app/out/full/ .

FROM oven/bun:1.3.3-slim AS runner
WORKDIR /app
COPY --from=installer /app .
WORKDIR /app/backend/layer2ledger

ENV SEED_CONFIG_PATH=/app/test-seed-config.json
ENV TESTHELPER_BASE_URL=http://layer2ledger-testhelper:8001

CMD ["bun", "run", "test/seed.ts"]
