[project]
name = "layer2bridge"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "base58>=2.1.1",
    "bip-utils>=2.9.3",
    "fastecdsa>=3.0.1",
    "pydantic>=2.12.5",
    "sqlalchemy>=2.0.47",
    "config-models",
    "config-loader",
    "layer2address",
    "layer1-utils",
    "openl2-messaging",
    "bitcoin-core-rpc",
    "openl2-layer2ledger-api",
    "httpx>=0.28.1"
]

[tool.uv.sources]
config-models = { path = "../packages/config_models", editable = true }
config-loader = { path = "../packages/config_loader", editable = true }
layer2address = { path = "../packages/layer2address", editable = true }
layer1-utils = { path = "../packages/layer1_utils", editable = true }
openl2-messaging = { path = "../packages/openl2_messaging", editable = true }
bitcoin-core-rpc = { path = "../packages/bitcoin_core_rpc", editable = true }
openl2-layer2ledger-api = { path = "../packages/openl2_layer2ledger_api", editable = true }

[project.scripts]
layer2bridge = "layer2bridge.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-asyncio>=1.3.0",
    "pytest-mock>=3.15.1",
]

[tool.hatch.build.targets.wheel]
packages = ["src/layer2bridge"]
