# generated by datamodel-codegen:
#   filename:  GetTransactionsResponse.json
#   timestamp: 2025-04-26T22:30:00+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel

from .CommonResponse import CommonResponse


class GetTransactionsResponseTransaction(BaseModel):
    amount: int = None
    destination_address_pubkey: str = None
    fee: int = None
    layer1_transaction_id: str = None
    layer2_withdrawal_id: str = None
    signature: str = None
    signature_date: str = None
    source_address_pubkey: str = None
    timestamp: int = None
    transaction_id: str = None
    transaction_type: int = None


class TransactionGroup(BaseModel):
    public_key: str = None
    transactions: List[GetTransactionsResponseTransaction] = None


class GetTransactionsResponse(CommonResponse):
    transactions: List[TransactionGroup] = None
