[build-system]
requires = ["hatchling"]  # or "setuptools>=61.0"
build-backend = "hatchling.build"  # or "setuptools.build_meta"

[project]
name = "layer2ledgerbatched"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "base58>=2.1.1",
    "bip-utils>=2.9.3",
    "fastapi>=0.116.1",
    "fastecdsa>=3.0.1",
    "pydantic>=2.11.7",
    "redis[hiredis]>=6.4.0",
    "sqlalchemy[asyncio]>=2.0.43",
    "uvicorn>=0.35.0",
    "config-models"
]

[dependency-groups]
dev = [
    "mypy>=1.17.1",
    "pytest>=8.4.1",
    "httpx>=0.28.1",
    "pytest-asyncio>=1.2.0",
]

[tool.uv]
package = true

[tool.uv.sources]
config-models = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/layer2ledgerbatched"]

#[tool.hatch.build.targets.wheel]
#packages = ["src/layer2ledgerbatched"]
#only-include = ["src/layer2ledgerbatched"]

#[tool.hatch.build.targets.sdist]
#packages = ["src/layer2ledgerbatched"]
