export const LABELS = {
	// General Actions
	BUTTON_REFRESH: "Refresh",
	BUTTON_REFRESHING: "Refreshing...",
	BUTTON_TRANSFER: "Transfer",
	BUTTON_SENDING: "Sending...",
	BUTTON_WITHDRAW: "Withdraw",
	BUTTON_WITHDRAWING: "Withdrawing...",
	BUTTON_DEPOSIT: "Deposit",
	BUTTON_GENERATING: "Generating...",
	BUTTON_GET_DEPOSIT_ADDRESS: "Get Deposit Address",
	BUTTON_MAX: "Max",
	BUTTON_SEARCH: "Search",
	BUTTON_HIDE: "Hide",
	BUTTON_CANCEL: "Cancel",
	BUTTON_HIDE_PERMANENTLY: "Hide Permanently",
	BUTTON_RESTORE_WALLET: "Restore Wallet",
	BUTTON_RESTORE: "Restore",

	// Transaction List / Explorer
	HEADING_RECENT_TRANSACTIONS: "Recent Transactions",
	TEXT_LOADING_TRANSACTIONS: "Loading transactions...",
	TEXT_NO_TRANSACTIONS: "No transactions found.",
	TEXT_TRANSACTION_NOT_FOUND: "Transaction not found.",
	HEADING_TRANSACTION_DETAILS: "Transaction Details",
	TEXT_SEARCHING: "Searching...",
	DIALOG_HIDE_MNEMONIC_TITLE: "Hide Mnemonic?",
	DIALOG_HIDE_MNEMONIC_DESC:
		"This will hide the mnemonic. Make sure you copied it down as it cannot be displayed again.",

	// Transaction Types
	TX_TYPE_TRANSFER: "Transfer",
	TX_TYPE_DEPOSIT: "Deposit",
	TX_TYPE_WITHDRAWAL_INITIATED: "Withdrawal Initiated",
	TX_TYPE_WITHDRAWAL_BROADCASTED: "Withdrawal Broadcasted",
	TX_TYPE_WITHDRAWAL_CANCELED: "Withdrawal Canceled",
	TX_TYPE_WITHDRAWAL_CONFIRMED: "Withdrawal Confirmed",
	TX_TYPE_UNKNOWN: "Unknown",

	// Transaction Item Keys
	KEY_ID: "ID:",
	KEY_TYPE: "Type:",
	KEY_AMOUNT: "Amount:",
	KEY_FEE: "Fee:",
	KEY_FROM: "From:",
	KEY_TO: "To:",
	KEY_DATE: "Date:",
	KEY_SIGNATURE: "Signature:",
	KEY_LAYER1_TXID: "Layer1 TxID:",
	VALUE_PENDING: "Pending",

	// Amount Input
	PLACEHOLDER_ENTER_AMOUNT: "Enter amount",
	TITLE_USE_MAX_BALANCE: "Use max balance",

	// Profiler Stats
	HEADING_PROFILER_STATS: "Profiler Stats",
	TEXT_PROFILER_STATS_DESC:
		"Visualize a profiler session: average replica concurrency, pushTransaction entry/exit, dbwriter writes, Redis queue depth, and pushTransaction section timings.",
	PLACEHOLDER_PROFILER_SESSION_ID: "Profiler session id",
	BUTTON_LOAD_STATS: "Load",
	TEXT_LOADING_PROFILER_SESSION: "Loading profiler session...",
	TEXT_PROFILER_SESSION_NOT_FOUND: "Profiler session not found.",
	TEXT_PROFILER_CHART_CONCURRENCY_TITLE: "Concurrency",
	TEXT_PROFILER_CHART_CUMULATIVE_TITLE: "Cumulative counts",
	TEXT_PROFILER_CHART_QUEUE_TITLE: "Redis pending queue",
	TEXT_PROFILER_CHART_WRITE_ACTIVE_TITLE: "Dbwriter activity",
	TEXT_PROFILER_CHART_SECTION_AVG_TITLE: "pushTransaction section timing",
	TEXT_PROFILER_CHART_CONCURRENCY_AXIS: "Count",
	TEXT_PROFILER_CHART_CUMULATIVE_AXIS: "Cumulative count",
	TEXT_PROFILER_CHART_QUEUE_AXIS: "Pending transactions",
	TEXT_PROFILER_CHART_WRITE_ACTIVE_AXIS: "State (0/1)",
	TEXT_PROFILER_CHART_SECTION_AVG_AXIS: "Avg ms",
	TEXT_PROFILER_CHART_AVG_CONCURRENT: "Avg replica concurrency",
	TEXT_PROFILER_CHART_QUEUE_DEPTH: "Pending transactions",
	TEXT_PROFILER_CHART_WRITE_ACTIVE: "dbwriter writing to Postgres",
	TEXT_PROFILER_CHART_SLEEP_ACTIVE: "dbwriter sleeping / inactive",
	TEXT_PROFILER_CHART_REDIS_ACTIVE: "dbwriter Redis housekeeping",
	TEXT_PROFILER_CHART_SECTION_VALIDATE: "validate",
	TEXT_PROFILER_CHART_SECTION_VERIFY_SIGNATURE: "verify signature",
	TEXT_PROFILER_CHART_SECTION_ACQUIRE_LOCK: "acquire lock",
	TEXT_PROFILER_CHART_SECTION_DUPLICATE_CHECK: "duplicate check",
	TEXT_PROFILER_CHART_SECTION_GET_BALANCE: "get balance",
	TEXT_PROFILER_CHART_SECTION_ENQUEUE: "enqueue",
	TEXT_PROFILER_CHART_PUSH_ENTRIES: "pushTransaction entries",
	TEXT_PROFILER_CHART_PUSH_EXITS: "pushTransaction exits",
	TEXT_PROFILER_CHART_WRITES: "dbwriter writes",
	TEXT_PROFILER_STAT_TOTAL_TXS_PER_SEC: "Total txs/s",
	TEXT_PROFILER_STAT_THROUGHPUT_START_MS: "Total txs/s start (ms)",
	TEXT_PROFILER_STAT_THROUGHPUT_END_MS: "Total txs/s end (ms)",
	TEXT_PROFILER_STAT_THROUGHPUT_MARKER_HINT:
		"Click to show/hide marker. Drag the vertical bar on a chart to set time.",
	TEXT_PROFILER_VIEW_RANGE: "View range (ms)",
	LABEL_PROFILER_VIEW_START: "View start",
	LABEL_PROFILER_VIEW_END: "View end",
	TEXT_PROFILER_CHART_MARKER_START: "txs/s start",
	TEXT_PROFILER_CHART_MARKER_END: "txs/s end",
	TEXT_PROFILER_STAT_PUSH_TXS_PER_SEC: "Push txs/s",
	TEXT_PROFILER_STAT_PEAK_CONCURRENT: "Peak concurrent",
	TEXT_PROFILER_STAT_DBWRITER_WRITES: "Dbwriter writes",
} as const;

export const TEST_IDS = {
	BALANCE_DISPLAY: "balance-display",
	TRANSACTION_TITLE: "transaction-item-title",
	RESTORE_WALLET_TRIGGER: "restore-wallet-trigger",
	MNEMONIC_INPUT: "mnemonic-input",
	RESTORE_WALLET_BUTTON: "restore-wallet-button",
} as const;
