# generated by datamodel-codegen:
#   filename:  SearchRequest.json
#   timestamp: 2025-04-06T21:23:46+00:00

from __future__ import annotations


from pydantic import BaseModel

class SearchRequest(BaseModel):
    search_string: str
    search_type: str
