# generated by datamodel-codegen:
#   filename:  RequestWithdrawalRequest.json
#   timestamp: 2025-04-06T21:23:56+00:00

from __future__ import annotations

from pydantic import BaseModel


class RequestWithdrawalRequest(BaseModel):
    amount: int
    layer1_withdrawal_address: str
    layer2_transaction_id: str # Client generated
    signature: str
    source_address_public_key: str
