[project]
name = "setup-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "config-models",
    "config-loader",
    "misc-utils",
    "layer2address",
    "configobj>=5.0.9",
]

[tool.uv]
package = true

[tool.uv.sources]
config-models = { path = "../packages/config_models", editable = true }
config-loader = { path = "../packages/config_loader", editable = true }
misc-utils = { path = "../packages/misc_utils", editable = true }
layer2address = { path = "../packages/layer2address", editable = true }

[tool.hatch.build.targets.wheel]
packages = ["src/setup_scripts"]

[build-system]
requires = ["hatchling"]  # or "setuptools>=61.0"
build-backend = "hatchling.build"  # or "setuptools.build_meta"
