# generated by datamodel-codegen:
#   filename:  GetBalanceRequest.json
#   timestamp: 2025-04-06T21:23:54+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class GetBalanceRequest(BaseModel):
    public_keys: List[str] = None
