# generated by datamodel-codegen:
#   filename:  GetTransactionsRequest.json
#   timestamp: 2025-04-06T21:23:57+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class GetTransactionsRequest(BaseModel):
    public_keys: list[str] = None
