# generated by datamodel-codegen:
#   filename:  GetTransactionRequest.json
#   timestamp: 2025-04-06T21:23:50+00:00

from __future__ import annotations


from pydantic import BaseModel


class GetTransactionRequest(BaseModel):
    transaction_id: str = None
