# generated by datamodel-codegen:
#   filename:  SearchResultsResponse.json
#   timestamp: 2025-04-26T22:30:02+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from .CommonResponse import CommonResponse


class GetBalanceResponseBalance(BaseModel):
    address_found: bool = None
    balance: int = None
    public_key: str = None


class GetTransactionsResponseTransaction(BaseModel):
    amount: int = None
    destination_address_pubkey: str = None
    fee: int = None
    layer1_transaction_id: str = None
    layer2_withdrawal_id: str = None
    signature: str = None
    signature_date: str = None
    source_address_pubkey: str = None
    timestamp: int = None
    transaction_id: str = None
    transaction_type: int = None


class SearchResultsResponse(CommonResponse):
    l2_address: GetBalanceResponseBalance = None
    l2_transaction: GetTransactionsResponseTransaction = None
    search_string: str = None
    search_type: str = None
