runtime: python38

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

env_variables:
  REDISHOST: '[IP]'
  REDISPORT: '[PORT]'
  REDISAUTH: '[AUTHKEY]'
  NODE_ID: ''
  DEPOSIT_WALLET_MASTER_PUBKEY: ''
  FULLNODE_SIGNING_KEY_PUBKEY: ''
  ONBOARDING_DEPOSIT_SIGNING_KEY_PRIVKEY: ''
  ONBOARDING_DEPOSIT_SIGNING_KEY_PUBKEY: ''
  MINIMUM_LAYER1_TRANSACTION_AMOUNT: 1000

vpc_access_connector:
  name: projects/[PROJECT-NAME]/locations/[LOCATION]/connectors/addressbalancecache